### ISSUE TITLE
data in panel doesnt load properly in extreme dash breakout

### ISSUE THREAD

**Issue by Mkrummz** [mikempx/Extreme-Dashboard-Makeover#21]
Convert the 'Server Request Rates' panel from the deprecated "graph" panel to a bar gauge panel section doesnt load the data properly... it does load it properly if you import the final dashboard

**Comment by hedss** [comment]
Is this different to the library panel issue where using Grafana Data doesn't actually show anything until you save and reload the dashboard (which I was told was expected behaviour)?

**Comment by Mkrummz** [comment]
no different issue

**Comment by hedss** [comment]
TestDB data wasn't loading correctly, this has now been fixed in the latest Grafana 10.2.x version. Can't remember the issue number off top of head though.
